server:
  port: 8080

spring:
  application:
    name: lambda-client-app
  
aws:
  lambda:
    function-url: ${LAMBDA_FUNCTION_URL:https://your-lambda-function-url.lambda-url.us-east-1.on.aws/}
    region: ${AWS_REGION:us-east-1}
    timeout-seconds: ${LAMBDA_TIMEOUT:30}

logging:
  level:
    com.example.lambdaclient: INFO
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
